apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2023-09-17T11:31:08Z"
  generation: 4
  labels:
    app.kubernetes.io/component: code-runner-component
    app.kubernetes.io/instance: code-runner-instance
    app.kubernetes.io/name: code-runner
  name: code-runner
  namespace: default
  resourceVersion: "32810920"
  uid: 2cbf0c0a-745d-42ad-9f9b-9f41c37e37a5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: code-runner-instance
      app.kubernetes.io/name: code-runner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-10-03T17:39:19Z"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: code-runner-component
        app.kubernetes.io/instance: code-runner-instance
        app.kubernetes.io/name: code-runner
    spec:
      containers:
      - image: registry.digitalocean.com/mufti-api/code-runner
        imagePullPolicy: Always
        name: code-runner
        ports:
        - containerPort: 8000
          name: api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-mufti-api
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-10-02T11:08:33Z"
    lastUpdateTime: "2023-10-02T11:08:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-09-17T11:42:40Z"
    lastUpdateTime: "2023-10-03T17:39:23Z"
    message: ReplicaSet "code-runner-6b964c4484" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
